# -*- coding: utf-8 -*-
"""midterm_assessment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JDmWbLZ2TdCrPt8GR3CGJYmOvWkqxpp

# MIDTERM ASSESSMENT_ BY ABDULSAMAD NURADEEN

**Predicting Housing Prices in Buenos Aires Project!**

## Import for this project
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.metrics import mean_absolute_error
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import Ridge
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline, make_pipeline
from glob import glob
# %matplotlib inline

"""# DATA CLEANING AND PREPARATION"""

def wrangle(filepath):
  df = pd.read_csv(filepath)

  # Subset property in `"Capital Federal"`
  mask_ba = df['place_with_parent_names'].str.contains('Capital Federal')

  # Subset to apartment
  mask_apt = df['property_type'] == 'apartment'

  # Subset property where `"price appro usd"` < 400,000
  mask_price = df['price_aprox_usd'] < 400_000

  df = df[mask_ba & mask_apt & mask_price]

  # Remove outliers
  low, high = df['surface_covered_in_m2'].quantile([0.1, 0.9])
  mask_area = df['surface_covered_in_m2'].between(low, high)
  df = df[mask_area]

  # Split "lat-lon" columns
  df[['lat', 'lon']] = df['lat-lon'].str.split(",", expand=True).astype(float)
  df.drop(columns=['lat-lon'], inplace=True)

  # Extract neighborhood
  df['neighborhood'] = df["place_with_parent_names"].str.split("|", expand=True)[3]
  df.drop(columns='place_with_parent_names', inplace=True)

  # drop feature with high null value
  df.drop(columns=['floor', 'expenses'], inplace=True)

  # drop low and high cardinaly columns
  df.drop(columns=['operation', 'property_type', 'properati_url', 'currency'], inplace=True)

  # drop leaky columns
  df.drop(
        columns=[
            'price',
            'price_aprox_local_currency',
            'price_per_m2',
            'price_usd_per_m2'
        ], inplace=True
    )

  # Drop multiple linear colinearity
  df.drop(columns=["surface_total_in_m2", "rooms"], inplace=True)

  return df

files = glob('/content/buenos-aires-real-estate-*.csv')
frames = [wrangle(file) for file in files]
df = pd.concat(frames, ignore_index=True)
print('df shapes: ', df.shape)
df.head()

"""# EXPLORATORY DATA ANALYSIS(EDA)

**Distribution of Apartment Sizes**
"""

plt.hist(df["surface_covered_in_m2"])
plt.xlabel("Area [sq meters]")
plt.title("Distribution of Apartment Sizes")

"""### The relationship between Area and Price"""

plt.scatter(x=df['surface_covered_in_m2'], y=df['price_aprox_usd'])
plt.xlabel('Area [sq meters]')
plt.ylabel('Price [USD]')
plt.title('Buenos Aires: Area vs Price ')

"""### The relationship between Location and Price"""

fig = px.scatter_mapbox(
    df,  # Our DataFrame
    lat= "lat",
    lon= "lon",
    width=600,  # Width of map
    height=600,  # Height of map
    color= "price_aprox_usd",
    hover_data=["price_aprox_usd"],  # Display price when hovering mouse over house
)

fig.update_layout(mapbox_style="open-street-map")

fig.show()

"""# DATASET SPLITTING"""

target = "price_aprox_usd"
y_train = df[target]
X_train = df.drop(columns=target)
X_train.head()

"""# DEVELOPING A MODEL

**Baseline model**
"""

y_mean = y_train.mean()
y_mean

y_pred_baseline = [y_mean] * len(y_train)
y_pred_baseline[:2]

"""**Mean Absolute Error**"""

mae_baseline = mean_absolute_error(y_train, y_pred_baseline)

print("Mean apt price", round(y_mean, 2))
print("Baseline MAE:", round(mae_baseline, 2))

"""**Building a model**"""

model = make_pipeline(
    OneHotEncoder(handle_unknown='ignore'),
    SimpleImputer(),
    Ridge()
)
model.fit(X_train, y_train)

"""**Train a model**"""

y_pred_training = model.predict(X_train)
y_pred_training[:5]

"""**model evaluation**"""

mae_training = mean_absolute_error(y_train, y_pred_training)
print("Training MAE:", round(mae_training, 2))

"""**testing a model**"""

X_test = pd.read_csv("/content/buenos-aires-test-features.csv")
y_pred_test = pd.Series(model.predict(X_test))
y_pred_test.head()

"""# Communicate Results

**Coefficients and Intercepts**
"""

def make_prediction(area, lat, lon, neighborhood):
    data = {
        "surface_covered_in_m2": area,
        "lat": lat,
        "lon": lon,
        "neighborhood": neighborhood
    }
    df = pd.DataFrame(data=data, index=[0])
    prediction = model.predict(df).round(2)[0]
    return f"Predicted apartment price: ${prediction}"

make_prediction(110, -34.60, -58.46, "Villa Crespo")

